service: flavioaandres-services
frameworkVersion: '2'

plugins: 
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  MediumCollector:
    handler: handler.mediumCollector
  GetMediumPosts:
    handler: handler.getMediumPosts
    events: 
      - http:
          path: /posts
          method: GET
          cors:
            - enabled: true
            - origin: "'*'"
            - headers: "Access-Control-Allow-Origin"
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"