service: flavioaandres-services
frameworkVersion: '2'

plugins: 
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  RSSCollector:
    handler: handler.RSSCollector
    events: 
      - schedule: 
          rate: 'rate(12 hours)'
  GetEntities:
    handler: handler.getRSSData
    events: 
      - http:
          path: /posts
          method: GET
          cors:
            origin: "*"
            headers: "Access-Control-Allow-Origin"
          response:
            headers:
              Access-Control-Allow-Origin: "*"